### ISSUE TITLE
Removing unused CSS

### ISSUE THREAD

**Issue by MalayaliRobz** [emberjs-chennai/website#13]
Right now the whole of tailwind CSS file is being called on the website.

instead, use Purgecss tool to inject just the required css files.
Refer: https://tailwindcss.com/docs/controlling-file-size

**Comment by gokatz** [comment]
Will look into this.

**Comment by gokatz** [comment]
Plan:
* Move from `ember-cli-tailwind` to directly utilize Tailwind CSS version > 1.0. This [issue](https://github.com/embermap/ember-cli-tailwind/issues/143) contains more info
* Move from `ember-cli-sass` to postCSS sass plugins as tailwind and PurgeCSS are easily configurable using [PostCSS](https://tailwindcss.com/docs/installation/#4-process-your-css-with-tailwind) [plugins](https://tailwindcss.com/docs/controlling-file-size/#setting-up-purgecss)

**Comment by gokatz** [comment]
#21 upgrades tailwind to 1.1.2

**Comment by MalayaliRobz** [comment]
https://github.com/emberjs-chennai/website/pull/25 solves this
